In [ ]:
# https://www.techbeamers.com/python-generate-random-numbers-list/
# 

In [21]:
# list of integers
my_list = [1, 2, 3]

In [22]:
# empty list
my_list = []

# list with mixed data types
my_list = [1, "Hello", 3.4]

In [23]:
# nested list
my_list = ["mouse", [8, 4, 6], ['a']]

# Using random.sample() 

* We can also use the sample() method available in random module to directly generate a list of random numbers.Here we specify a range and give how many random numbers we need to generate.

In [24]:
import random
 
# using random.sample()
# to generate random number list
res = random.sample(range(1, 50), 7)
 
# printing result
print ("Random number list is : " +  str(res))

Random number list is : [20, 32, 5, 27, 38, 14, 40]


In [ ]:
import random
#Generate 5 random numbers between 10 and 30
randomlist = random.sample(range(10, 30), 5)
print(randomlist)

# using list comprehension + randrange()
# to generate random number list

In [25]:
import random
 

res = [random.randrange(1, 50, 1) for i in range(7)]
 
# printing result
print ("Random number list is : " +  str(res))

Random number list is : [32, 46, 43, 1, 8, 2, 8]


# Method #3: Using numpy.random

## 1. Generating a list of random integers using numpy.random.randint function
* This function returns random integers from the “discrete uniform” distribution of the integer data type.

In [ ]:
# random.randint(Start, Stop)

In [1]:
# Don't call `random.seed()` yet
import random
random.random()

0.5140118307529379

In [2]:
random.random()

0.5008091412373166

* If you run this code yourself, I’ll bet my life savings that the numbers returned on your machine will be different. The default when you don’t seed the generator is to use your current system time or a “randomness source” from your OS if one is available.

* With random.seed(), you can make results reproducible, and the chain of calls after random.seed() will produce the same trail of data:

In [11]:
random.seed(444)

random.random()

0.3088946587429545

In [5]:
random.random()

0.01323751590501987

In [12]:
random.seed(444)
random.random()

0.3088946587429545

In [13]:
random.random()

0.01323751590501987

In [ ]:
import random
n = random.random()
print(n)

* Generating Number in a Range
* The randint() method generates a integer between a given range of numbers.

In [ ]:
import random
n = random.randint(0,22)
print(n)

* Generating a List of numbers Using For Loop

In [ ]:
import random
randomlist = []
for i in range(0,5):
n = random.randint(1,30)
randomlist.append(n)
print(randomlist)

In [ ]:
import numpy as np
 
# print the list of 10 integers from 3  to 7
print(list(np.random.randint(low = 3,high=8,size=10)))
 
# print the list of 5 integers from 0 to 2
# if high parameter is not passed during
# function call then results are from [0, low)
print(list(np.random.randint(low = 3,size=5)))

## 2. Generating list of random floating values using numpy.random.random_sample function
* This function return random float values in half open interval [0.0, 1.0).

In [ ]:
import numpy as np
 
# generates list of 4 float values
print(np.random.random_sample(size = 4))
 
# generates 2d list of 4*4
print(np.random.random_sample(size = (4,4)))

# Method 4: Using random module

In [ ]:
import random
 
rand_list=[]
n=10
for i in range(n):
    rand_list.append(random.randint(3,9))
print(rand_list)

In [ ]:
# https://realpython.com/python-random/

##  PRNGs for Arrays: numpy.random
* One thing you might have noticed is that a majority of the functions from random return a scalar value (a single int, float, or other object). If you wanted to generate a sequence of random numbers, one way to achieve that would be with a Python list comprehension

In [14]:
[random.random() for _ in range(5)]

[0.4844375347808497,
 0.8614799253779063,
 0.7426396870165088,
 0.6338658027451068,
 0.4419557492849159]

In [15]:
random.random() for _ in range(5)

SyntaxError: invalid syntax (<ipython-input-15-c07c833b585c>, line 1)

In [16]:
import numpy as np
np.random.seed(444)
np.set_printoptions(precision=2) 

In [17]:
# Return samples from the standard normal distribution
np.random.randn(5)


array([ 0.36,  0.38,  1.38,  1.18, -0.94])

In [18]:
 np.random.randn(3, 4)


array([[-1.14, -0.54, -0.55,  0.21],
       [ 0.21,  1.27, -0.81, -3.3 ],
       [-0.81, -0.36, -0.88,  0.15]])

In [19]:
 # `p` is the probability of choosing each element
np.random.choice([0, 1], p=[0.6, 0.4], size=(5, 4))

array([[0, 0, 1, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 1]])

In [20]:
# NumPy's `randint` is [inclusive, exclusive), unlike `random.randint()`
np.random.randint(0, 2, size=25, dtype=np.uint8).view(bool)

array([ True, False,  True,  True, False,  True, False, False, False,
       False, False,  True,  True, False, False, False,  True, False,
        True, False,  True,  True,  True, False,  True])