For the $O(n^2)$ algorithm, we check every element in the list with the elements succeeding that element, and if we find a match, we store it in another array (duplicate_array). In the end, we return the duplicate_array from our function. Since every element is compared with the succeeding elements, the total number of comparisons will be:
$$ (n-1)+(n-2)+....+1 = \dfrac{n(n-1)}{2} = O(n^2)$$

In [26]:
import timeit

In [27]:
# O(n^2) Algorithm

def find_duplicates_n2(array):
    
    duplicate_array = []
    
    for i in range(len(array)-1):
        
        for j in range(i+1, len(array)):
            
        
            if(array[i]==array[j]):
                
                if array[i] in duplicate_array: break
                    
                
                else:
                    duplicate_array.append(array[i])
                    
                    return duplicate_array
                        
                    
            
                   
                
            
               

In [24]:
find_duplicates_n2(['homework', 'assignment', 'quiz', 'discussion', 'quiz', 'program'])

['quiz']

In [28]:
print(timeit.timeit(find_duplicates_n2(['homework', 'assignment', 'quiz', 'discussion', 'quiz', 'program']), number=1))

ValueError: stmt is neither a string nor callable

In [9]:

arr = [1, 2, 3, 4, 2, 7, 8, 8, 3];   
   
print("Duplicate elements in given array: ");  
#Searches for duplicate element  
for i in range(0, len(arr)):  
    for j in range(i+1, len(arr)):  
        if(arr[i] == arr[j]):  
            print(arr[j]);  

Duplicate elements in given array: 
2
3
8


In [16]:
import random
import numpy as np
arr =np.array(random.sample(range(1, 200), 150))
print("Duplicate elements in given array: ");  
#Searches for duplicate element  
for i in range(0, len(arr)):  
    for j in range(i+1, len(arr)):  
        if(arr[i] == arr[j]):  
            print(arr[j]);  


Duplicate elements in given array: 


In [1]:
#O(N^2) complexity :

# list to store the data to be looped
ls = ["homework", "assignment", "quiz", "discussion", "quiz", "program"]

#O(N^2) complexity solution
for i in range(len(ls)):
    for j in range(i+1,len(ls)):
        if( ls[i] == ls[j]):
            print("Yes, there is a duplicate. [e.g. '{}']".format(ls[i]))

Yes, there is a duplicate. [e.g. 'quiz']


For the $O(n)$ algorithm, one may use a Hashmap. In Python, this can be implemented using dictionaries. We maintain the count of each item in the dictionary. The first time we encounter the item, we create a key in the dictionary and initialize the count of that particular item to one. If we again encounter the item, we just increment the count of the corresponding key by 1. Since this is a hashmap, the "finding the key" step takes $O(1)$ time. As we repeat the same for all elements ($n$) of the array, we expect the process to take $O(n)$ time.

Finally we go through the dictionary and print the values (or store the values in another array which can be returned by a function). This step takes less than $O(n)$ time, making the whole process an $O(n)$ algorithm.


In [40]:
# O(n) Algorithm

def find_duplicates_n(array):
    duplicate_dict = {}
    for element in array:
        try: duplicate_dict[element] += 1
        except: duplicate_dict[element] = 1
        duplicate_array = [element for element in duplicate_dict if(duplicate_dict[element] > 1)]
        return duplicate_array
find_duplicates_n(['homework', 'assignment', 'quiz', 'discussion', 'quiz', 'program'])              

[]

In [41]:
# O(N) complexity :

# list to store the data to be looped
ls = ["homework", "assignment", "quiz", "discussion", "quiz", "program"]

#O(N) complexity solution
dict = {}

for i in range(len(ls)):
    if(ls[i] in dict):
        print("Yes, there is a duplicate. [e.g. '{}']".format(ls[i]))
    else : 
        #insert into dictionary if data is not there
        dict[ls[i]] = ls[i]

Yes, there is a duplicate. [e.g. 'quiz']


In [ ]:
# O(n) if dict is hash, O(nlogn) if dict is tree, and simple, fixed. Thanks to Matthew for the suggestion.


In [1]:
lst = [8, 8, 9, 9, 7, 15, 15, 2, 20, 13, 2, 24, 6, 11, 7, 12, 4, 10, 18, 13, 23, 11, 3, 11, 12, 10, 4, 5, 4, 22, 6, 3, 19, 14, 21, 11, 1, 5, 14, 8, 0, 1, 16, 5, 10, 13, 17, 1, 16, 17, 12, 6, 10, 0, 3, 9, 9, 3, 7, 7, 6, 6, 7, 5, 14, 18, 12, 19, 2, 8, 9, 0, 8, 4, 5]

In [3]:
def unique(lst):
    
    output = []
    
    y = {}
    
    for item in lst:
        
        y[item] = ""

    for item in lst:
        
        if item in y:
            
            output.append(item)
            

            return output
unique(lst)

[8]

In [ ]:
#has_key in python is O(1). Insertion and retrieval from a hash is also O(1). Loops through n items twice, so O(n).

In [12]:
def del_dups(seq):
    
    seen = {}
    pos = 0
    for item in seq:
        if item not in seen:
            seen[item] = True
            seq[pos] = item
            pos += 1
    del seq[pos:]

lst_1 = [8, 8, 9, 9, 7, 15, 15, 2, 20, 13, 2, 24, 6, 11, 7, 12, 4, 10, 18, 
       13, 23, 11, 3, 11, 12, 10, 4, 5, 4, 22, 6, 3, 19, 14, 21, 11, 1, 
       5, 14, 8, 0, 1, 16, 5, 10, 13, 17, 1, 16, 17, 12, 6, 10, 0, 3, 9, 
       9, 3, 7, 7, 6, 6, 7, 5, 14, 18, 12, 19, 2, 8, 9, 0, 8, 4, 5,6,1,1,
      3,3,4,4,5,5,6,6,11,11,17,17,21,21,23,23,23,25,25,27,27,29,29,29,0]
del_dups(lst_1)
print(lst_1)

[8, 9, 7, 15, 2, 20, 13, 24, 6, 11, 12, 4, 10, 18, 23, 3, 5, 22, 19, 14, 21, 1, 0, 16, 17, 25, 27, 29]


In [ ]:
#https://dev.to/chiefcode/timing-python-code-snippet-3dnk

In [ ]:
print(timeit.timeit(myFunction, number=1))

In [ ]:
# https://www.tutorialspoint.com/generating-random-number-list-in-python

In [45]:
import random

In [49]:
def del_dups(seq):
    
    seen = {}
    pos = 0
    for item in seq:
        if item not in seen:
            seen[item] = True
            seq[pos] = item
            pos += 1
    del seq[pos:]

randomlist = random.sample(range(1, 200), 150)
del_dups(randomlist)
print(randomlist)
print(timeit.timeit(, number=1))





[28, 37, 112, 193, 138, 118, 12, 73, 7, 188, 124, 10, 151, 189, 145, 144, 60, 140, 141, 9, 156, 199, 40, 79, 111, 22, 72, 71, 47, 20, 150, 29, 61, 177, 129, 81, 76, 110, 165, 192, 27, 64, 3, 89, 178, 26, 109, 94, 125, 95, 25, 55, 8, 142, 183, 122, 62, 161, 42, 100, 162, 160, 123, 33, 169, 91, 154, 34, 93, 198, 99, 74, 51, 83, 104, 53, 65, 137, 11, 157, 149, 23, 58, 35, 181, 45, 152, 131, 86, 172, 105, 146, 96, 115, 170, 164, 24, 90, 187, 88, 32, 119, 54, 127, 148, 14, 130, 190, 49, 78, 134, 82, 66, 67, 167, 197, 116, 132, 128, 92, 179, 136, 57, 16, 97, 176, 121, 75, 2, 5, 13, 68, 158, 36, 38, 135, 48, 185, 56, 103, 184, 1, 59, 84, 153, 107, 44, 113, 87, 120]


NameError: name 'seq' is not defined

In [3]:
#Below is the program with O(n2) complexity:

# program to check the presence of duplicates in the file
lst = [x for x in range(10000)]
lst.append(9999) # to insure the duplicate element is present

# O(n2) program
for i in range(0, len(lst)  - 1):
    for j in range(i + 1, len(lst)):
        if(lst[i] == lst[j]) :
            print("duplicate present")
            break

duplicate present


In [5]:
#Below is the program with O(n) complexity:

# program to check the presence of duplicates in the file
lst = [x for x in range(10000)]
lst.append(9999) # to insure the duplicate element is present

# O(n) program
check_elmnt= [0 for i in range(10000 + 1)] # maintaining the array to check if the element is present or not in the list

for i in range(0, len(lst)):
    if check_elmnt[lst[i]] == 0:
         check_elmnt[lst[i]] = 1;
    else :
        print("duplicate present")
        break


duplicate present


In [1]:
import timeit
import time

In [2]:
def  On2():
    lst = [x for x in range(10000)]
    lst.append(9999)
    for i in range(0, len(lst)  - 1):
        for j in range(i + 1, len(lst)):
            if(lst[i] == lst[j]) :
                print("duplicate present")
                break
print(timeit.timeit(stmt='On2()', setup='from __main__ import On2', number=1))

duplicate present
5.036530800000008


In [ ]:
import timeit
import time

In [3]:
def ON():
    lst = [x for x in range(10000)]
    lst.append(9999)
    check_elmnt= [0 for i in range(10000 + 1)]
    for i in range(0, len(lst)):
        if check_elmnt[lst[i]] == 0:
         check_elmnt[lst[i]] = 1;
        else :
          print("duplicate present")
        break

print(timeit.timeit(stmt='ON()', setup='from __main__ import ON', number=1))

0.0007577999999739404


## HOMEWORK-5

###  first will take n^k where n is the number of elements in the list and k is total list since we are accessing the all elements


In [1]:
# minimum from list of list

def findMinimum(num):
    minimum=9999
    for i in range(len(num)):
        for j in range(len(num[i])):
            if minimum>num[i][j]:
                minimum=num[i][j]
                return minimum

In [2]:
num=[[5,2,31,9],[2,1,6,7,11],[55,1,7,8,9]]
print('Minimum using linear search: ',findMinimum(num))

Minimum using linear search:  5


### for second question we are sorting each list and one list will take to sort nlogn time so to sort all list it will take knlogn as there are k list to sort. and now to compare all elements with zeroth element of every ;list will take k time so  knlogn+k so overall time complexity =knlogn.


In [3]:
def findMinUsingSorting(num):
    minimum=999999999
    for i in range(len(num)):
        num[i].sort()
        if minimum>num[i][0]:
            minimum=num[i][0]
            return minimum

In [4]:
num=[[5,2,31,9],[2,1,6,7,11],[55,1,7,8,9]]

print('Minimum using sorting: ',findMinUsingSorting(num))

Minimum using sorting:  2


In [6]:
import numpy as np
matrix = np.random.randint(2,20, size=(50,50))

print('Minimum using linear search: ',findMinimum(matrix))
print('Minimum using sorting: ',findMinUsingSorting(matrix))

Minimum using linear search:  17
Minimum using sorting:  2


### Work Place

In [26]:
import numpy as np
import timeit
import time

## O(N^k) notation..   with list of list
### In the belowe code we are using two loops one inside the other so time complexity will be O(nk)where k=2.

In [28]:
num_list = [[5,2,31,9],[2,1,6,7,11],[55,1,7,8,9]]
def minElement(num_list):
    minimum = min(num_list[0])
    for i in num_list:
        mini = min(i)
        if minimum > mini:
            minimum = mini
            return minimum
print(minElement(num_list))
print(timeit.timeit(stmt='minElement("num_list")', setup='from __main__ import minElement', number=1))

1
2.7000000955013093e-06


### I converted the list you gave to matrix.

In [29]:
num_list_matrix = np.asarray(num_list)
def minElementMatrix(num_list_matrix):
    minimum = min(num_list_matrix[0])
    for i in num_list_matrix:
        mini = min(i)
        if minimum > mini:
            minimum = mini
            return minimum
print(minElement(num_list_matrix))
print(timeit.timeit(stmt='minElementMatrix("num_list_matrix")', setup='from __main__ import minElementMatrix', number=1))

1
2.699999868127634e-06


In [30]:
print(num_list_matrix)
print(num_list_matrix.shape)
type(num_list_matrix)

[list([5, 2, 31, 9]) list([2, 1, 6, 7, 11]) list([55, 1, 7, 8, 9])]
(3,)


numpy.ndarray

## Q-3
## O(N^k)
## I would create a 50x50 matrix

In [32]:
import random
np.random.seed(41)
matrix_50 = np.random.randint(1,20, size=(50,50))
print(matrix_50.shape)
type(matrix_50)


(50, 50)


numpy.ndarray

In [17]:
import timeit
import time
import numpy as np
matrix_50

def minElement(matrix_50):
    minimum = min(matrix_50[0])
    for i in matrix_50:
        mini = min(i)
        if minimum > mini:
            minimum = mini
            return minimum
print(minElement(matrix_50))
print(timeit.timeit(stmt='minElement("matrix_50")', setup='from __main__ import minElement', number=1))

None
4.400000022997119e-06


### and did not give the smallest value here  WHY?

## Q-2
### O(NlogN)

 To improve the time complexity we will sort each list using sorting with O(nlogn) time complexity

 we will take the first element of each nested list ( we used the Extract() function in below code) and find minimum which will take O(n) time so overall time complexity will be O(nlogn) + O(n) = O(nlogn) as O(n) is smaller so we remove that part.

In [14]:
import timeit
import time
num_list = [[5,2,31,9],[2,1,6,7,11],[55,1,7,8,9]]
for i in num_list:
    i.sort()
def FirstONlogN(num_list):
    return [item[0] for item in num_list]

minimum = min(FirstONlogN(num_list))
print(minimum)
print(timeit.timeit(stmt='FirstONlogN("num_list")', setup='from __main__ import FirstONlogN', number=1))

1
2.300000005561742e-06


### I would convert list of list to matrix

In [35]:
%%time
import timeit
import time
import numpy as np
num_list_matrix = np.asarray(num_list)

for i in num_list_matrix:
    i.sort()
def FirstONlogN(num_list_matrix):
    return [item[0] for item in num_list_matrix]

minimum = min(FirstONlogN(num_list_matrix))
print(minimum)
print(timeit.timeit(stmt='FirstONlogN("num_list_matrix")', setup='from __main__ import FirstONlogN', number=1))

1
2.999999651365215e-06
Wall time: 0 ns


### Q-3
###  O(NlogN) with matrix(50x50) 

In [38]:
matrix = np.random.randint(1,20, size=(50,50))
print(matrix)
print(matrix.shape)
type(matrix)

[[18  2  3 ... 11 15 14]
 [15 19 19 ...  5 14 14]
 [ 6 10 11 ... 15  4 11]
 ...
 [17 15  6 ... 15 15  9]
 [ 4  7 16 ...  4  1  4]
 [ 6  2  1 ...  8  9 19]]
(50, 50)


numpy.ndarray

In [43]:
%%time
import timeit
import time
import numpy as np
matrix = np.array(np.random.randint(1,20, size=(50,50)))
for i in matrix:
    i.sort()
def FirstONlogN(matrix):
    return [item[0] for item in matrix]

minimum = min(FirstONlogN(matrix))
print(minimum)
print(timeit.timeit(stmt='FirstONlogN("matrix")', setup='from __main__ import FirstONlogN', number=1))

1
2.8999997994105797e-06
Wall time: 1.99 ms


In [19]:
import numpy as np
matrix_z = np.zeros((50,50))
matrix_z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
type(matrix_z)

numpy.ndarray

In [2]:
import timeit
import time
import numpy as np
matrix_z = np.zeros((50,50))


def minElement(matrix_z):
    minimum = min(matrix_z[0])
    for i in matrix_z:
        return minimum
    mini = min(i)
    if minimum > mini:
        minimum = mini
            
print(minElement(matrix_z))
print(timeit.timeit(stmt='minElement("matrix_z")', setup='from __main__ import minElement', number=1))

0.0
1.7000002117129043e-06


In [52]:
#import numpy
#i = 50
#matrix = numpy.zeros(shape=(i,i))
#for i in range(5):
  #  matrix[0][i] = i+1
  #  matrix[i][0] = i+1
#print(matrix)

matrix=[]

for i in range(50):
    row=[] 
    for j in range(50):
        row.append(0)
        matrix.append(row)
        return matrix
    
#print(matrix)

In [56]:
import numpy as np

def minElement(matrix):
    minimum = min(matrix[0])
    for i in matrix:
        mini = min(i)
        if minimum > mini:
            minimum = mini
            return minimum
print(minElement(matrix))

None


In [57]:
import numpy as np

for i in matrix :
    i.sort()
def FirstExtract(matrix ):
    return [item[0] for item in matrix ]

minimum = min(FirstExtract(matrix))
print(minimum)

1


### Timing

In [7]:
%%time
print("this code is to demonstration time complexity!")

this code is to demonstration time complexity!
Wall time: 0 ns


In [8]:
%%time 
for i in range(10):
    print("this code demonstration time complexity!")

this code demonstration time complexity!
this code demonstration time complexity!
this code demonstration time complexity!
this code demonstration time complexity!
this code demonstration time complexity!
this code demonstration time complexity!
this code demonstration time complexity!
this code demonstration time complexity!
this code demonstration time complexity!
this code demonstration time complexity!
Wall time: 4 ms


### Convert a list of numbers to a matrix

In [7]:
A = np.asarray(num_list)
A

array([list([5, 2, 31, 9]), list([2, 1, 6, 7, 11]),
       list([55, 1, 7, 8, 9])], dtype=object)

In [8]:
type(A)

numpy.ndarray

In [9]:
A.shape

(3,)

In [10]:
A.dtype

dtype('O')

In [15]:
empty_array = np.empty((50,50), dtype=int)

In [17]:
print(empty_array)
type(empty_array)

[[-1979121616         538 -1994508736 ...           0           0
            0]
 [          0           0           0 ...           0           0
            0]
 [          0           0           0 ...           0           0
            0]
 ...
 [          0           0           0 ...           0           0
            0]
 [          0           0           0 ...           0           0
            0]
 [          0           0           0 ...           0           0
            0]]


numpy.ndarray

### Discussion 5

In [1]:
import timeit
import time
import numpy as np
def binary_search(data, value):
    n = len(data)
    left = 0
    right = n - 1
    while left <= right:
        middle = (left + right) // 2
        if value < data[middle]:
            right = middle - 1
        elif value > data[middle]:
            left = middle + 1
        else:
            return middle
    raise ValueError('Value is not in the list')
    
if __name__ == '__main__':
    data = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    print(binary_search(data, 8))
    print(timeit.timeit(stmt='binary_search('data', 'value')', setup='from __main__ import binary_search', number=1))

7


## Homework-5

In [5]:
def AllSubsets_Rec(arr, n, v, sum):
    if (sum == 0):
        for value in v :
            print(value, end=" ")
        print()
        return
    if (n == 0):
        return
        
    AllSubsets_Rec(arr, n - 1, v, sum)
        
    v1 = [] + v
    v1.append(arr[n - 1])
    AllSubsets_Rec(arr, n - 1, v1, sum - arr[n - 1])
        
        
def All_Subsets(arr, n, sum):
    v = []
    AllSubsets_Rec(arr, n, v, sum)
arr = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

sum = 23

n = len(arr)

All_Subsets(arr, n, sum)
        

7 6 4 3 2 1 
7 6 5 3 2 
7 6 5 4 1 
8 5 4 3 2 1 
8 6 4 3 2 
8 6 5 3 1 
8 6 5 4 
8 7 4 3 1 
8 7 5 2 1 
8 7 5 3 
8 7 6 2 
9 5 4 3 2 
9 6 4 3 1 
9 6 5 2 1 
9 6 5 3 
9 7 4 2 1 
9 7 4 3 
9 7 5 2 
9 7 6 1 
9 8 3 2 1 
9 8 4 2 
9 8 5 1 
9 8 6 
10 5 4 3 1 
10 6 4 2 1 
10 6 4 3 
10 6 5 2 
10 7 3 2 1 
10 7 4 2 
10 7 5 1 
10 7 6 
10 8 3 2 
10 8 4 1 
10 8 5 
10 9 3 1 
10 9 4 
11 5 4 2 1 
11 5 4 3 
11 6 3 2 1 
11 6 4 2 
11 6 5 1 
11 7 3 2 
11 7 4 1 
11 7 5 
11 8 3 1 
11 8 4 
11 9 2 1 
11 9 3 
11 10 2 
12 5 3 2 1 
12 5 4 2 
12 6 3 2 
12 6 4 1 
12 6 5 
12 7 3 1 
12 7 4 
12 8 2 1 
12 8 3 
12 9 2 
12 10 1 
12 11 
13 4 3 2 1 
13 5 3 2 
13 5 4 1 
13 6 3 1 
13 6 4 
13 7 2 1 
13 7 3 
13 8 2 
13 9 1 
13 10 
14 4 3 2 
14 5 3 1 
14 5 4 
14 6 2 1 
14 6 3 
14 7 2 
14 8 1 
14 9 
15 4 3 1 
15 5 2 1 
15 5 3 
15 6 2 
15 7 1 
15 8 
16 4 2 1 
16 4 3 
16 5 2 
16 6 1 
16 7 
17 3 2 1 
17 4 2 
17 5 1 
17 6 
18 3 2 
18 4 1 
18 5 
19 3 1 
19 4 
20 2 1 
20 3 


In [ ]:
def AllSubsetsRec(array, sum_, partial=[]):
    a=[]
    s = 0
    for i in partial:
        s+=i
   
   # check if the partial sum is equals to desired sum 23
   if s == sum_: 
       a.append(partial)
       print(a)
   
   if s >= sum_:
       return  # if we reach the number why we will  return back  
   
   for i in range(len(array)):
       n = array[i] # here it will take one number from array and try to add numbers in partial till we find the sum
       remaining = array[i+1:]
       pairs_sum(remaining, sum_, partial + [n]) # here recusion is used
   


pairs_sum([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],23)

In [11]:
def All_Subsets_Rec(arr, _sum, part=[]):              #----------------------------->
    a=[]                                              #----------------------------->
    s = 0                                             #----------------------------->
    
    for i in part:                                    #----------------------------->
        s+=i                                          #----------------------------->
    if s == _sum:                                     #----------------------------->
        a.append(part)                                #----------------------------->
        print(a)                                      #----------------------------->
    if s >= _sum:                                     #----------------------------->
        return                                        #----------------------------->
    for i in range(len(arr)):                         #----------------------------->
        n = arr[i]                                    #----------------------------->
        remaining= arr[i+1:]                          #----------------------------->
        All_Subsets_Rec(remaining, _sum, part + [n])  #----------------------------->
                
All_Subsets_Rec([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],23)                

[[1, 2, 3, 4, 5, 8]]
[[1, 2, 3, 4, 6, 7]]
[[1, 2, 3, 4, 13]]
[[1, 2, 3, 5, 12]]
[[1, 2, 3, 6, 11]]
[[1, 2, 3, 7, 10]]
[[1, 2, 3, 8, 9]]
[[1, 2, 3, 17]]
[[1, 2, 4, 5, 11]]
[[1, 2, 4, 6, 10]]
[[1, 2, 4, 7, 9]]
[[1, 2, 4, 16]]
[[1, 2, 5, 6, 9]]
[[1, 2, 5, 7, 8]]
[[1, 2, 5, 15]]
[[1, 2, 6, 14]]
[[1, 2, 7, 13]]
[[1, 2, 8, 12]]
[[1, 2, 9, 11]]
[[1, 2, 20]]
[[1, 3, 4, 5, 10]]
[[1, 3, 4, 6, 9]]
[[1, 3, 4, 7, 8]]
[[1, 3, 4, 15]]
[[1, 3, 5, 6, 8]]
[[1, 3, 5, 14]]
[[1, 3, 6, 13]]
[[1, 3, 7, 12]]
[[1, 3, 8, 11]]
[[1, 3, 9, 10]]
[[1, 3, 19]]
[[1, 4, 5, 6, 7]]
[[1, 4, 5, 13]]
[[1, 4, 6, 12]]
[[1, 4, 7, 11]]
[[1, 4, 8, 10]]
[[1, 4, 18]]
[[1, 5, 6, 11]]
[[1, 5, 7, 10]]
[[1, 5, 8, 9]]
[[1, 5, 17]]
[[1, 6, 7, 9]]
[[1, 6, 16]]
[[1, 7, 15]]
[[1, 8, 14]]
[[1, 9, 13]]
[[1, 10, 12]]
[[2, 3, 4, 5, 9]]
[[2, 3, 4, 6, 8]]
[[2, 3, 4, 14]]
[[2, 3, 5, 6, 7]]
[[2, 3, 5, 13]]
[[2, 3, 6, 12]]
[[2, 3, 7, 11]]
[[2, 3, 8, 10]]
[[2, 3, 18]]
[[2, 4, 5, 12]]
[[2, 4, 6, 11]]
[[2, 4, 7, 10]]
[[2, 4, 8, 9]]
[[2, 4, 17]]
[[2, 5

In [ ]:
# its complexity will be 0(n^2) 

#because for loop is running two times one in main code and one in recursion

In [ ]:
const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,16,17,18,19,20]--------->O(1)

/* sum: total of each subset
   result: output triplets
   subset: flag to dismiss used along with partial size(3), if one of them is true, returns null
   n: each item in the array, evantuall added into partial array of 3 items
   remaining: each item is copied into result array if total is 23
*/
const sum = 23--------->O(1)
let result = null--------->O(1)
let subset, n, remaining--------->O(1)

/* numbers: Array
   target: 23
   partial: each item of triplets, adding each value should be equal to target
*/
function subset_sum(numbers, target, partial = []) {
    
    subset = partial.reduce( (a, b) => a + b, 0)--------->O(1)

    if (subset > target || partial.length >= 20) return null--------->O(n)
    
    check23(subset, partial);--------->O(1)

    for (let i = 0; i < numbers.length; i++) {--------->O(n)
        n = numbers[i]
        remaining = numbers.slice(i + 1)
        subset_sum(remaining, target, partial.concat([n]))
    }

    return result  --------->O(1)
}

/* validate if the partial items sum equals to total 23 */
const check23 = (subset, partial) => {
    if (subset === 23) {
        if(!result) 
        result = []
        result.push(partial)
    }
}


console.log(subset_sum(arr, sum))



In [ ]:
Time Complexity: O(n^2) in worst case.
Nested loop is used to traverse the array so the time complexity is O(n^2)